### ISSUE TITLE
invoice delete problem

### ISSUE THREAD

**Issue by pdryl** [cschalenborgh/php-invoiceocean#3]
yours API methods array states:  'deleteInvoice' =>  'invoices.json' but it should be 'deleteInvoice' =>  'invoices/[ID].json' 
I belive this causes problem with invoice delete

**Comment by mariusz-zajac** [comment]
I fixed it in #4 , but it's not accepted yet. Try it out.

**Comment by cschalenborgh** [comment]
I've accepted the PR @mariusz-zajac . Thanks!
